### PR TITLE
update environment and lock files

### PR DESCRIPTION
**Pull request by tsnow03**
Copying the [environment](https://github.com/CryoInTheCloud/hub-image/blob/main/environment.yml) from the [hub-image](https://github.com/CryoInTheCloud/hub-image/issues) repo and adding a lock file. The old lock file isn't working and package updates for jupyter book will be really nice to have.

### CODE REVIEW

**Comment by weiji14** [comment]
@tsnow03, is this just syncing the CryoCloudWebsite's environment.yml file with the one at https://github.com/CryoInTheCloud/hub-image/blob/13c06aff40c93435f0b7c44d02e74f24e381b02a/environment.yml?

**Comment by tsnow03** [comment]
I'd like to. I'm not actually getting a lock file that builds properly. I'll work on this tomorrow.

**Comment by weiji14** [comment]
Are you getring the same error as in https://github.com/conda/conda-lock/issues/292? Might need to downgrade to `conda=22.9`.

**Comment by tsnow03** [comment]
I'm using conda=4.13.0. I was able to build the new conda lock file, but using `conda env create --name cryocloud --file conda-linux-64.lock.yml` it will not create a new environment. 
`Solving environment: failed

ResolvePackageNotFound: 
  - nss==3.78=h2350873_0
  - kealib==1.4.15=ha7026e8_1
  - postgresql==14.5=ha105346_1
  - xorg-libxau==1.0.9=h7f98852_0
  - blosc==1.21.1=h83bc5f7_3
  - icu==70.1=h27087fc_0
  - kiwisolver==1.4.4=py39hf939315_1
  - libgfortran-ng==12.2.0=h69a702a_19
  - .....`

**Comment by weiji14** [comment]
> I'm using conda=4.13.0. I was able to build the new conda lock file, but using `conda env create --name cryocloud --file conda-linux-64.lock.yml` will not create a new environment.

Hmm, `conda=4.13.0` is a little old now (released [20 May 2022](https://github.com/conda/conda/releases/tag/4.13.0)). Maybe try updaing it using `conda update -n base conda` and try again?

Looking through the packages you listed like `nss`, `kealib`, `postgresql`, etc. It seems that the `conda=4.13.0` is picking up slightly older versions which are packaged using the `.tar.bz2` archive format, even though conda-forge has moved to the a more lightweight `.conda` format by default now (see https://github.com/conda-forge/conda-forge.github.io/issues/1586). Still, I don't see why you wouldn't be able to install either of them with `conda=4.13.0` (would maybe ask @scottyhq), but maybe updating your `conda` installer to a `22.*` version can help :shrug:

**Pull request closed without merging**
