### PR TITLE
Add nbgitpuller

### PR DESCRIPTION
**Pull request by weiji14**
Jupyter server extension to sync a git repository one-way to a local path!

Context is to get a Binder environment setup for an [ESIP ML Tutorial](https://www.esipfed.org/lab/funding-opportunities/ml-rfp) I'll be working on that uses ICESat-2 ATL11 data. For now, I'm trying to get things to work using https://jupyterhub.github.io/nbgitpuller/link.html with the following configurations:

BinderHub URL: https://staging.aws-uswest2-binder.pangeo.io
Git Environment Repository URL: https://github.com/CryoInTheCloud/CryoCloudWebsite (`add-nbgitpuller` branch)
Git Content Repository URL: https://github.com/weiji14/deepicedrain (`main` branch)

### CODE REVIEW

**Comment by weiji14** [comment]
Am getting some weird errors at https://staging.aws-uswest2-binder.pangeo.io/v2/gh/CryoInTheCloud/CryoCloudWebsite/add-nbgitpuller?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fweiji14%252Fdeepicedrain%26urlpath%3Dlab%252Ftree%252Fdeepicedrain%252F%26branch%3Dmain. Here's part of it typed out (couldn't copy the error messages out of that box...)

```
Encountered problems while solving.
Problem: nothing provides __unix needed by pysocks-1.7.1-pyha2e5f31_6
Problem: nothing provides __linux needed by terminado-0.16.0-pyh41d4057_0
Problem: nothing provides __linux needed by ipython-8.5.0-pyh41d4057_1
Problem: nothing provides __linux needed by ipykernel-6.16.0-pyh210e3f2_0
```
image

My guess is that [Pangeo Binder](https://github.com/pangeo-data/pangeo-binder) is using a somewhat old Python 3.7 version (and/or mamba 0.5.1), but the CryoCloudWebsite environment is Python 3.9? Or maybe I'm not using nbgitpuller correctly. May need to think about this a bit more.

**Comment by weiji14** [comment]
Don't merge this yet. I'm still trying to work out some dependency related issues (unsure yet whether it's a problem on Pangeo Binder or here in the cryocloud docker image).

**Comment by weiji14** [comment]
Ready to review (and merge if ok)! There's still some issues but I think it's on the Pangeo BinderHub side and not here on the CryoCloud docker image, so the changes here should be good to go.

**Comment by scottyhq** [comment]
@weiji14 unfortunately the pangeo-binder on AWS isn't being updated or maintained anymore. I'd recommend using https://mybinder.org instead (although the obvious drawback being you're not running in AWS us-west-2 which is required for cloud access to NSIDC IS2 data)!

For reference, the existing pangeo-binder is using an old version of repo2docker to build the images which is where the old mamba version comes from. https://github.com/pangeo-data/pangeo-binder/blob/3af202d8800576547105a13a533964830e9930b9/pangeo-binder/values.yaml#L5-L7

I opened an issue a while back on jupyterbook that is relevant for a workaround using pre-build images https://github.com/executablebooks/jupyter-book/issues/1235 

Or perhaps 2i2c will start up a standard binderhub in AWS? https://github.com/2i2c-org/infrastructure/issues/919

**Comment by weiji14** [comment]
Ah yes, thanks for those links (especially to the Pangeo Binder config)! You've got a sharp eye that I'm looking for a Binder deployment on aws-uswest2 :nerd_face: It's been a challenge to get the data (NSIDC ICESat-2 on aws-uswest-2) and software environment (customized using Binder) to be aligned, and https://staging.aws-uswest2-binder.pangeo.io seemed like the most promising if not for the lack of maintenance! I'll keep an eye on the 2i2c AWS BinderHub deployment, that seems like the most robust solution, though it can't come soon enough!

In the meantime, I'm going to workaround the situation at https://github.com/geo-smart/deepicedrainpipe/pull/1 by mimicking the CryoCloud conda enviroment (which is mostly just `icepyx`). The `nbgitpuller` addition here should streamline things a little bit by being able to sync the `git` version controlled code to the CryoCloud JupyterHub.

**Review by tsnow03 — APPROVED** [review]

**Pull request merged**
