### PR TITLE
Updating ATL15 tutorial with icepyx updates

### PR DESCRIPTION
**Pull request by tsnow03**

### CODE REVIEW

**Comment by JessicaS11** [comment]
This PR is a follow up on #89, which needed to be merged before the ATL15 tutorial was completely updated because the [corresponding icepyx PR](https://github.com/icesat2py/icepyx/pull/516) is still awaiting review (any volunteers?)

**Comment by JessicaS11** [comment]
Hey @wsauthoff - not sure why this branch was closed but it's still active. I actually was planning to complete it a couple weeks ago when I learned that geopandas has moved their underlying map layers to an external library, which no longer includes the countries layer because it indicates political boundaries. As a result, the sections of the tutorial using the "Greenland" polygon no longer work (I believe they were part of the notebook you developed originally), so I was unable to update the icepyx-related outputs and merge this PR.

**Comment by wsauthoff** [comment]
> Hey @wsauthoff - not sure why this branch was closed but it's still active. I actually was planning to complete it a couple weeks ago when I learned that geopandas has moved their underlying map layers to an external library, which no longer includes the countries layer because it indicates political boundaries. As a result, the sections of the tutorial using the "Greenland" polygon no longer work (I believe they were part of the notebook you developed originally), so I was unable to update the icepyx-related outputs and merge this PR.

Hi @JessicaS11, I didn't realize it was still active. I was trying clean up my local and remote branches. Major apologies!

**Comment by JessicaS11** [comment]
> I made changes to the ATL15 lakes tutorial notebook that fixes the deprecated geopandas code in this https://github.com/CryoInTheCloud/CryoCloudWebsite/pull/109.

Can you share how this new notebook is meant to interface with the existing one? On a first quick read-through it appears to have a lot of similar content to the existing notebook. I'll also note it doesn't appear to have been added to the TOC.

> I'm just having an issue with GitHub indicating there are conflicts in the feature branch within that tutorial notebook that I haven't been able to figure out just yet.

It looks like their are still conflicts. I'll see if I can figure them out.

**Comment by JessicaS11** [comment]
@wsauthoff I got all the conflicts resolved and it's looking great. Somehow all the changes meant that the GitHub history of the branch was suddenly very different from my local copy, which didn't help!

I'd like to recommend that we move the non-ATL15 content (so the earthaccess data access) to a different notebook. It aligns nicely with some content the CryoCloud book already has on accessing NASA data (so perhaps should be integrated into those tutorials or put adjacent to them?), but feels very off topic to include in this one.

**Comment by JessicaS11** [comment]
I'm apparently also not able to render the notebook outputs - all the figure cells result in a: `Error displaying widget: model not found`. Do I need to install something to my local hub?

**Comment by JessicaS11** [comment]
@wsauthoff I created a copy of this tutorial [(`earthaccess-stream.ipynb`)](https://github.com/CryoInTheCloud/CryoCloudWebsite/tree/earthaccess-stream/book/tutorials/IS2_ATL15_surface_height_anomalies) that still contains the earthaccess streaming section and put it in the "earthaccess-stream" branch so you can easily find the content if you want to integrate it into another section. Then I removed that content from this ATL15 tutorial. I would still be curious how this tutorial is meant to align with the other ATL15 one, as I think it will be confusing for users to have two that are so similar.

**Review by JessicaS11 — APPROVED** [review]

**Pull request merged**
