### PR TITLE
updated workflow figure and changed title levels

### PR DESCRIPTION
**Pull request by jkingslake**
@tsnow03 if we have time this merge would updated the workflow figure in the ARCO notebook and change title levels.

### CODE REVIEW

**Comment by tsnow03** [comment]
This has some conflicts with the main branch. I'm just getting onto my flight. Would you be able to resolve these?

**Comment by jkingslake** [comment]
Yeah, I am not sure why these conflicts have turned up. I'm on the plane now, so I'll try to sort this out tonight, but it's not a big deal for tomorrow if we don't get these edits in there.

**Comment by tsnow03** [comment]
Hi Jonny, are you still wanting to push these changes into our JupyterBook or should I close this?

**Comment by jkingslake** [comment]
Yes, I think these edits are not needed anymore, if #87 is merged.

**Pull request closed without merging**
